services:
  - type: web
    name: myf-candidature-frontend
    runtime: static
    buildCommand: "node -e \"console.log('Frontend original prêt')\""
    staticPublishPath: ./public
    routes:
      - type: rewrite
        source: /api/*
        destination: https://46-224-141-132.sslip.io/api/*
    headers:
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
