services:
  - type: web
    name: agent-ia-myf
    env: node
    plan: free

    envVars:
      - key: NODE_VERSION
        value: 20.11.1

      - key: NODE_ENV
        value: production
      - key: DATA_DIR
        value: /data
      - key: MISTRAL_API_KEYS
        sync: false
      - key: ADMIN_KEY
        sync: false

    buildCommand: npm install
    startCommand: node server.js

    disk:
      name: myf-database
      mountPath: /data
      sizeGB: 1
