name: Keep Render Alive

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping server
        run: curl -s https://agent-myf-cvlm-1.onrender.com/
